(define (problem turtlebot_demo_task)
(:domain turtlebot_demo)
(:objects
    robot1 robot2 robot3 - robot
    a1 a2 a3 b1 b2 b3 c1 c2 c3 - waypoint
)
(:init
    (connected a1 a2)
    (connected a1 b1)
    (connected a2 a1)
    (connected a2 a3)
    (connected a3 a2)
    (connected a3 b3)
    (connected b1 a1)
    (connected b1 b2)
    (connected b1 c1)
    (connected b2 b1)
    (connected b2 b3)
    (connected b3 a3)
    (connected b3 b2)
    (connected b3 c3)
    (connected c1 b1)
    (connected c1 c2)
    (connected c2 c1)
    (connected c2 c3)
    (connected c3 c2)
    (connected c3 b3)
    (free b1)
    (free b2)
    (free b3)
    (free c1)
    (free c2)
    (free c3)
    (robot_at robot1 a1)
    (robot_at robot2 a2)
    (robot_at robot3 a3)
)
(:goal (and
    (robot_at robot1 c1)
    (robot_at robot2 c2)
    (robot_at robot3 c3)
    (visited robot1 b2)
    (visited robot2 b2)
    (visited robot3 b2)
)))
